# Generated by Django 4.1.1 on 2022-09-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='Building Powerful Minds Through Mathematics', max_length=500, verbose_name='Main Heading')),
                ('main_description', models.TextField(default='Our award winning K-12 after-school math program has empowered students to achieve excellence for over twenty years.', verbose_name='Hero Description')),
                ('main_side_image', models.ImageField(default='https://russianschool-tinypng.s3.us-east-1.amazonaws.com/uploads/home2-min1576261723-2x1583938060-2x.1584953668_1x.png', help_text='Upload PNG', upload_to='uploads', verbose_name='Side Image')),
                ('rsm_online', models.CharField(default='RSM Online', max_length=50, verbose_name='Title')),
                ('rsm_phone', models.CharField(default='(617) 362 3500', max_length=50, verbose_name='Phone No')),
                ('rsm_link', models.URLField(default='online.elementary@russianschool.com', max_length=50, verbose_name='Link')),
                ('our_program_heading', models.CharField(default='Our Programs', max_length=50, verbose_name='Header')),
                ('our_program_description', models.TextField(default='With multiple levels for every grade as well as a selective competitions program, we are able to best serve each child’s development based on his or her knowledge and ability.', verbose_name='Description')),
                ('our_result_heading', models.CharField(default='Our Results', max_length=50, verbose_name='Header')),
                ('our_result_description', models.TextField(default='Our students post remarkable scores on math competitions, see higher grades in school, and build a lasting confidence in their math and learning abilities overall.', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(default='Students are required to think their way through logic problems that can be resolved only with creative use of the math they’ve learned.', verbose_name='Review')),
                ('reviewer', models.CharField(default='The Boston Globe', max_length=50, verbose_name='Reviewer')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_front.indexpage', verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_heading', models.TextField(default='A+', verbose_name='Heading')),
                ('description', models.CharField(default='Our students experience soaring confidence and grades', max_length=50, verbose_name='Description')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_front.indexpage', verbose_name='Page')),
            ],
        ),
    ]
