# Generated by Django 4.1.1 on 2022-09-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='main_heading_2',
            field=models.CharField(default='Building Powerful Minds Through Mathematics', max_length=500, verbose_name='Main Heading'),
        ),
    ]
