# Generated by Django 4.1.1 on 2022-09-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_front', '0002_indexpage_main_heading_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='main_heading_2',
            field=models.CharField(default='We use the rigorous study of mathematics as a vehicle to develop our students’ math fluency, intellect, and character, empowering them for life.', max_length=500, verbose_name='Main Heading 2'),
        ),
    ]
