# Generated by Django 4.1.1 on 2022-09-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_front', '0004_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default='Elementary (K-2)', max_length=150, verbose_name='Program Name'),
        ),
    ]
